language: node_js
node_js:
  - "14"
cache:
  directories:
    - ./node_modules
dist: xenial
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lib.build
  - ng test --watch false --browsers ChromeHeadless

deploy:
  provider: pages
  skip_cleanup: true # To avoid cleanup of the artifact generated during script
  github_token: $GITHUB_TOKEN # Provided as an environment variable in travis
  local_dir: dist/libraries-project # Replace this with your project name
  on:
    branch: master
