language: node_js
node_js:
  - "14"
cache:
  directories:
    - ./node_modules
dist: xenial
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lib.build
  - ng test --watch false --browsers ChromeHeadless
  - ng build --configuration production

# Despliegue continuo
deploy:
  provider: pages
  skip_cleanup: true # To avoid cleanup of the artifact generated during script
  token: $GITHUB_TOKEN # Token proporcionado en las variables de entorno
  local_dir: dist/libraries-project # Referencia de donde está compilado el proyecto
  on:
    branch: master
