language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lib.build
  - npm run travis.app
  - npm run travis.lib
  - ng build --prod --base-href https://mugan86.github.io/angular-github-widget/