language: node_js
node_js:
  - "14"
cache:
  directories:
    - ./node_modules
dist: xenial
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run lib.build
  - ng test --watch false --browsers ChromeHeadless
